import type { Comment, PostData } from './types'

export const sampleComments: Comment[] = [
  {
    id: '1',
    author: '베테랑게이머',
    authorLevel: 45,
    content: '신규 유저분들은 처음에 튜토리얼을 꼼꼼히 따라하시는게 좋아요. 기본기가 중요합니다!',
    date: '2025.07.19',
    likes: 5,
  },
  {
    id: '2',
    author: '도움러',
    authorLevel: 32,
    content: '캐릭터는 취향에 따라 선택하시면 되고, 레벨업은 데일리 퀘스트 위주로 하시면 효율적입니다.',
    date: '2025.07.19',
    likes: 3,
  },
]

export const allPosts: { [key: string]: PostData } = {
  '1': {
    id: '1',
    title: '2025.07.19 긴급 패치 사항',
    content: [
      '안녕하세요, 이프선셋 개발팀입니다.',
      '',
      '금일 오후 2시에 긴급 패치를 진행하였습니다.',
      '',
      '**패치 내용:**',
      '- 게임 크래시 현상 수정',
      '- 로딩 화면 최적화',
      '- 네트워크 연결 안정성 개선',
      '- UI 버그 수정',
      '',
      '**변경 사항:**',
      '1. 메인 메뉴 진입 시 발생하던 오류 해결',
      '2. 인벤토리 아이템 정렬 기능 개선',
      '3. 채팅 시스템 안정성 향상',
      '',
      '패치로 인해 불편을 드린 점 양해 부탁드리며, 더 나은 게임 환경을 위해 지속적으로 노력하겠습니다.',
      '',
      '감사합니다.',
    ].join('\n'),
    date: '2025.07.19',
    category: '공지',
    views: 1234,
    comments: 12,
    likes: 89,
    author: 'GM IfSunSets',
    isHot: true,
  },
  c1: {
    id: 'c1',
    title: '신규 유저입니다! 초보자 가이드 좀 알려주세요',
    content: [
      '안녕하세요! 오늘 처음 게임을 시작한 신규 유저입니다.',
      '',
      '게임이 정말 재밌어 보이는데 뭐부터 해야할지 모르겠어요ㅠㅠ',
      '',
      '1. 처음에 어떤 캐릭터를 선택하는게 좋을까요?',
      '2. 레벨업은 어떻게 빨리 할 수 있나요?',
      '3. 초보자가 주의해야 할 점이 있을까요?',
      '',
      '고수분들의 조언 부탁드립니다!',
    ].join('\n'),
    date: '2025.07.19',
    category: '질문',
    views: 156,
    comments: 8,
    likes: 12,
    author: '게임초보자',
    authorLevel: 1,
  },
}
